name = "MosimoMD"
uuid = "cd60d81d-79df-4a8f-b7fa-e1e735480e67"
authors = ["Sunoru <s@sunoru.com>"]
version = "0.1.0"

[deps]
MolecularDynamicsIntegrators = "293f545e-9dd2-11e9-1210-cf5bcdc9c322"
MosimoBase = "a39d5f18-f8b1-4777-8f97-f1f91469dbd0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
MolecularDynamicsIntegrators = "0.1"
MosimoBase = "0.3"
julia = "1.8"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Pkg"]
